# Generated by Django 6.1.1 on 2026-09-23 08:56

import django.db.models.deletion
import qr_tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(db_index=True, default=qr_tracker.models.generate_short_id, max_length=16, unique=True)),
                ('kind', models.CharField(choices=[('url', 'URL'), ('text', 'Texte'), ('wifi', 'WiFi'), ('email', 'Email'), ('phone', 'Téléphone'), ('vcard', 'vCard')], default='url', max_length=10)),
                ('target_url', models.URLField(blank=True, max_length=2000)),
                ('payload', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_tracker.qrlink')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['link', '-scanned_at'], name='qr_tracker__link_id_8c6792_idx')],
            },
        ),
    ]
