# Generated by Django 6.1.1 on 2026-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_tracker', '0002_qrlink_uniq_url_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
