# Generated by Django 6.1.1 on 2026-09-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_tracker', '0004_category_qrlink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlink',
            name='goal',
            field=models.PositiveIntegerField(default=0, help_text='Objectif de scans (0 = aucun).'),
        ),
        migrations.CreateModel(
            name='QRNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='qr_tracker.qrlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
