# Generated by Django 6.1.1 on 2026-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_tracker', '0005_qrlink_goal_qrnote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrlink',
            index=models.Index(fields=['-last_scanned_at'], name='qrlink_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='qrlink',
            index=models.Index(fields=['-scan_count'], name='qrlink_scans_idx'),
        ),
        migrations.AddIndex(
            model_name='qrlink',
            index=models.Index(fields=['-created_at'], name='qrlink_created_idx'),
        ),
        migrations.AddIndex(
            model_name='qrnote',
            index=models.Index(fields=['link', '-created_at'], name='note_link_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['link', 'ip_hash', 'scanned_at'], name='scan_cooldown_idx'),
        ),
    ]
