"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Charge BASE_DIR/.env (lignes CLE=valeur, sans dépendance) sans écraser l'environnement réel."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip().strip("'\"")
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv(BASE_DIR / ".env")

from django.core.exceptions import ImproperlyConfigured  # noqa: E402


def _required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise ImproperlyConfigured(
            f"Variable {name} manquante : renseignez-la dans l'environnement ou dans .env (voir .env.example)."
        )
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Pas de valeur par défaut : l'app refuse de démarrer sans vraie clé.
SECRET_KEY = _required_env("DJANGO_SECRET_KEY")

# Sûr par défaut : le local active explicitement True via .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h]
if DEBUG and 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

if not DEBUG:
    # Durcissement prod (HSTS, HTTPS, cookies sûrs).
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    # L'app n'envoie aucun e-mail (pas de SMTP à configurer).
    SILENCED_SYSTEM_CHECKS = ["mail.E001"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qr_tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# QR Tracker — comptage des scans (QR dynamiques).
# SHORT_BASE_URL doit être le domaine public pérenne en production,
# ex. https://qr.example.com (utilisé pour construire la short_url).
QR_TRACKER_SHORT_BASE_URL = os.environ.get('QR_SHORT_BASE_URL', 'http://127.0.0.1:8003')
QR_TRACKER_COOLDOWN_SECONDS = int(os.environ.get('QR_SCAN_COOLDOWN_SECONDS', '3600'))
# Pas de défaut : le sel pseudonymise les IP, il doit rester secret.
QR_TRACKER_IP_HASH_SALT = _required_env("QR_IP_HASH_SALT")
# Raccourcisseur : prod modérée (plan raccourcisseur-durl-intgr).
QR_TRACKER_CREATE_PER_HOUR = int(os.environ.get('QR_CREATE_PER_HOUR', '30'))
QR_TRACKER_BLOCKLIST = [d.strip().lower() for d in os.environ.get('QR_BLOCKLIST', '').split(',') if d.strip()]
QR_TRACKER_RETENTION_DAYS = int(os.environ.get('QR_RETENTION_DAYS', '180'))
QR_TRACKER_MAX_URL_LENGTH = int(os.environ.get('QR_MAX_URL_LENGTH', '2000'))
QR_TRACKER_MAX_PAYLOAD_LENGTH = int(os.environ.get('QR_MAX_PAYLOAD_LENGTH', '4000'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
